{
 "title": "Confluent Cloud",
 "tags": [ "confluent-cloud-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(confluent_kafka_server_retained_bytes, job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(confluent_kafka_server_retained_bytes{job=~\"$job\"}, kafka_id)"
    }
   },
   {
    "name": "topic",
    "label": "Topics",
    "query": {
     "query": "label_values(confluent_kafka_server_retained_bytes{job=~\"$job\",kafka_id=~\"$cluster\"}, topic)"
    }
   },
   {
    "name": "principal_id",
    "label": "Principal ID",
    "query": {
     "query": "label_values(confluent_kafka_server_request_count{job=~\"$job\", kafka_id=~\"$cluster\"},principal_id)"
    }
   },
   {
    "name": "connector_id",
    "label": "Connector",
    "query": {
     "query": "label_values(confluent_kafka_connect_dead_letter_queue_records{job=~\"$job\"}, connector_id)"
    }
   },
   {
    "name": "ksql_id",
    "label": "Ksql",
    "query": {
     "query": "label_values(confluent_kafka_ksql_streaming_unit_count{job=~\"$job\"}, ksql_id)"
    }
   },
   {
    "name": "schema_registry_id",
    "label": "Schema Registry",
    "query": {
     "query": "label_values(confluent_kafka_schema_registry_schema_count{job=~\"$job\"}, schema_registry_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Write on topics (rate)",
   "type": "stat",
   "description": "Per-second average rate of ingress of data to topics, basic cluster has a max of 100MBps.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(confluent_kafka_server_received_bytes{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"}[$__rate_interval])/count_over_time(confluent_kafka_server_received_bytes{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Read of topics (rate)",
   "type": "stat",
   "description": "Per-second average rate of egress data to topics, basic cluster has a max of 100MBps.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(confluent_kafka_server_sent_bytes{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"}[$__rate_interval])/count_over_time(confluent_kafka_server_sent_bytes{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Requests (rate)",
   "type": "stat",
   "description": "Per-second average rate of requests, basic cluster maxes out at 1500 requests per second.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(confluent_kafka_server_request_count{job=~\"$job\",kafka_id=~\"$cluster\",principal=~\"$principal_id\"}[$__rate_interval])/count_over_time(confluent_kafka_server_request_count{job=~\"$job\",kafka_id=~\"$cluster\",principal=~\"$principal_id\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Retained bytes",
   "type": "stat",
   "description": "Basic clusters have a max retained bytes limit of 5 TB prior to replication. confluent_kafka_server_retained_bytes is after replication thus needs to be divided by 3.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_retained_bytes{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"})/3"
    }
   ]
  },
  {
   "title": "Partition count ",
   "type": "stat",
   "description": "The sum of partitions in a cluster. Basic cluster max partitions limit is 2048.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_partition_count{job=~\"$job\",kafka_id=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "description": "The number of active connections to a cluster. Basic clusters limit active connections to 1000.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_active_connection_count{job=~\"$job\",kafka_id=~\"$cluster\",principal=~\"$principal_id\"})"
    }
   ]
  },
  {
   "title": "Successful authentications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_successful_authentication_count{job=~\"$job\",kafka_id=~\"$cluster\",principal=~\"$principal_id\"})"
    }
   ]
  }
 ]
}