{
 "title": "Consumer Client Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "client_id", "query": { "query": "label_values(client_id)" } },
   { "name": "env", "label": "env", "query": { "query": "label_values(env)" } },
   { "name": "consumer_group", "label": "consumer_group", "query": { "query": "label_values(group)" } },
   { "name": "topic", "label": "topic", "query": { "query": "label_values(topic)" } }
  ]
 },
 "panels": [
  {
   "title": "Average fetch throttle time",
   "type": "stat",
   "description": "The average time in ms a request was throttled by a broker.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_throttle_time_avg{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rebalance rate per hour",
   "type": "stat",
   "description": "The number of total rebalance events per hour, both successful and unsuccessful rebalance attempts.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_rebalance_rate_per_hour{} + kafka_consumer_failed_rebalance_rate_per_hour{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumer group lag in records ",
   "type": "timeseries",
   "description": "Offset lag per consumer group, summed by topic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_consumergroup_group_lag{group=~\"$consumer_group\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer group lag in seconds ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (topic) ((kafka_consumergroup_group_lag_seconds{group=~\"$consumer_group\"} > 0))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Fetch latency average",
   "type": "timeseries",
   "description": "The average time taken for a fetch request.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_latency_avg{client_id=~\"$client_id\", env=\"$env\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Bytes consumed rate",
   "type": "timeseries",
   "description": "The average number of bytes consumed per second\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_bytes_consumed_total{client_id=~\"$client_id\",env=~\"$env\",topic=~\"$topic\"}[$__rate_interval])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Consume request rate",
   "type": "timeseries",
   "description": "The average number of requests sent per second to the broker.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_request_total{client_id=~\"$client_id\",env=~\"$env\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{node_id}}"
    }
   ]
  },
  {
   "title": "Rate of records consumed",
   "type": "timeseries",
   "description": "The average number of records consumed per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_records_consumed_total{client_id=~\"$client_id\",env=~\"$env\",topic=~\"$topic\"}[$__rate_interval])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Consumer average fetch size",
   "type": "timeseries",
   "description": "The average number of bytes fetched per request per topic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_size_avg{client_id=~\"$client_id\",env=~\"$env\",topic=~\"$topic\"}",
     "legendFormat": "{{client_id}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Consumer fetch rate",
   "type": "timeseries",
   "description": "The number of fetch requests per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_fetch_rate{client_id=~\"$client_id\",env=~\"$env\"}[$__rate_interval])",
     "legendFormat": "{{client_id}}"
    }
   ]
  }
 ]
}