{
 "title": "Producer Client Metrics",
 "description": "Java client metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client_id",
    "query": {
     "query": "label_values(kafka_producer_app_info, client_id)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_producer_producer_topic_metrics_byte_total{job=\"producer\"}, topic)"
    }
   },
   { "name": "env", "query": { "query": "label_values(env)" } }
  ]
 },
 "panels": [
  {
   "title": "Retry rate",
   "type": "stat",
   "description": "The average per-second number of retried record sends for a topic. An increase could signal connectivity problems from the application to the broker. ",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_record_retry_rate{}",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Record error rate",
   "type": "stat",
   "description": "The average per-second number of record sends that resulted in errors.\n",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(kafka_producer_record_error_total{}[$__rate_interval])",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Free buffer space",
   "type": "stat",
   "description": "he total amount of buffer memory that is not being used (either unallocated or in the free list).",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_producer_buffer_available_bytes{}",
     "legendFormat": "Buffer bytes available"
    }
   ]
  },
  {
   "title": "Produce request throttle average",
   "type": "stat",
   "description": "The average time in ms a request was throttled by a broker.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_produce_throttle_time_avg{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Produce request latency",
   "type": "graph",
   "description": "The average request latency in ms.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_request_latency_avg{}",
     "legendFormat": "{{client_id}} - {{node_id}}"
    }
   ]
  },
  {
   "title": "Record queue time",
   "type": "graph",
   "description": "The average time in ms record batches spent in the send buffer.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_queue_time_avg{env=\"$env\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Batch size average",
   "type": "timeseries",
   "description": "The average number of bytes sent per partition per-request.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "kafka_producer_batch_size_avg{}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Outgoing byte rate",
   "type": "timeseries",
   "description": "The average number of bytes sent per second to the broker.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_outgoing_byte_total{}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{node_id}}"
    }
   ]
  },
  {
   "title": "Outgoing messages per second",
   "type": "timeseries",
   "description": "The average number of messages sent per second to the broker.\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_record_send_total{}[$__rate_interval])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Produce request rate",
   "type": "graph",
   "description": "The average number of requests sent per second to the broker.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_request_total{}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{node_id}}"
    }
   ]
  }
 ]
}